<div class="top-pad"></div>



<div class="content-padding">
	<br /><br /><br /><br /><br /><br />
	<div class="faq-sun"></div>
	<br /><br /><br /><br />
</div>

<div class="content-padding col-box" ng-controller="SupportCtrl">
	<div class="two-col">
		<br />
		<h4>Got an issue with an order?</h4>
		<p>Please contact Alpha Delta Pizza at <a href="tel:+12037873333">(203) 787-3333</a></p>
	</div>
	<div class="two-col">
		<h4>Want to launch your own One Button Wenzel?</h4>
		<p>The code is open source! Cause we are awesome. </p>
		<br /><br />
		<a href="https://github.com/crunchbutton" target="_blank"><button class="button green">Get the Code</button></a>
	</div>
</div>