<div class="top-pad"></div>

<div>

	<div class="content-padding-desktop">

		<div class="content-padding-mobile">
			<div ng-hide="account.user.has_auth">
				<div class="order-buttons">

					<br>
					<div class="button-pushable">
						<button class="button lightorange" ng-click="modal.signupOpen();">Create an account</button>
					</div>
					<br />
				</div>

			</div>

			<div ng-show="account.user.has_auth">

				<div class="order-buttons">

					<div class="col-box">

						<div class="hide-desktop button-refer">
							<a href="{{referral.sms}}">
								<button class="button lightorange">
									<i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;<span>Invite Friends</span>
								</button>
							</a>
						</div>


						<div class="divider"></div>

					</div>




				</div>
			</div>

		</div>
	</div>

	<div class="divider dots" ng-if="order.id"></div>
	<br><br>


	<div class="order-content col-box content-padding-desktop" ng-if="order.id">

		<div class="content-padding-mobile two-col">

			<div class="order-icon"><div class="icon-chef"></div></div>
			<div class="order-info">
				<p ng-if="order.delivery_service == 1">
					For updates on your order, please text your driver, whose number you'll be texted.
				</p>
				<p ng-if="order.delivery_service == 0">
					For updates on your order, please call
					<br /><b>{{order._restaurant_name}}: <a href="tel:{{order._restaurant_phone}}" target="_blank">{{ order._restaurant_phone | formatPhone }}</a></b>
					<br /><br />
				</p>
			</div>
			<div class="divider"></div>

		</div>

		<div class="divider dots spacer-two-two hide-desktop" ng-if="order.id"></div>

		<div class="content-padding-mobile two-col" ng-if="order.id">

			<div class="order-icon">
				<div ng-show="(order.delivery_type == 'delivery')" class="icon-delivery"></div>
				<div ng-hide="(order.delivery_type == 'delivery')" class="icon-takeout"></div>
			</div>
			<div class="order-info order-info-oneline">
				<p>
					<span ng-show="(order.delivery_type == 'delivery')">
						<p ng-show="!order.date_delivery_formatted">Delivery order</p>
						<p ng-show="order.date_delivery_formatted" class="order-info-address">Delivery around: {{order.date_delivery_formatted}}</p>
					</span>
					<span ng-hide="(order.delivery_type == 'delivery')">Takeout order</span>
				</p>
			</div>
			<div class="divider"></div>

			<div class="order-icon">
				<div ng-show="(order.pay_type == 'card')" class="icon-card"></div>
				<div ng-hide="(order.pay_type == 'card')" class="icon-cash"></div>
			</div>
			<div class="order-info order-info-oneline">
				<p>
					<span ng-show="(order.pay_type == 'card')">
						Paid <b>$<span ng-bind-html-unsafe="order.charged | formatPrice"></span></b>
						<span ng-show="order.campus_cash">&nbsp;by <b>{{order.campus_cash_name}}</b>
						<span ng-show="order.campus_cash_number"> - <b>{{order.campus_cash_number}}</b></span>
						</span>
						<span ng-show="!order.campus_cash">&nbsp;by card <span ng-show="order.card_ending">ending in <b>{{order.card_ending}}</b>
						</span>
						</span>
						<div class="credit" ng-show="!order.reward_delivery_free && (order.credit && order.credit > 0)">( ${{order._credit}} credit )</div>
					</span>
					<span ng-hide="(order.pay_type == 'card')">Pay <b>$<span ng-bind-html-unsafe="order.charged | formatPrice"></span></b> <span ng-show="(order.delivery_type == 'delivery')"> and tip</span> with <b>cash</b></span>
				</p>
			</div>

			<div class="divider"></div>


			<div class="order-icon"><div class="icon-user"></div></div>
			<div class="order-info">
				<p>
					{{order.name}}
					<br>{{ order.phone | formatPhone }}
				</p>
			</div>
			<div class="divider"></div>


			<span ng-if="order.delivery_type == 'delivery'">
				<div class="order-icon"><div class="icon-map-home"></div></div>
				<div class="order-info">
					<p class="order-info-address"><a href="{{order.mapLink}}" target="_system"><span ng-bind-html-unsafe="order.address | nl2br"></span></a></p>
					<br />
				</div>
				<div class="divider"></div>
			</span>

			<div ng-hide="(order.delivery_type == 'delivery')">
				<div class="order-icon"><div class="icon-map-restaurant"></div></div>
				<div class="order-info">
					<p class="order-info-address"><a href="{{order.mapLink}}" target="_system"><span ng-bind-html-unsafe="order._restaurant_address | nl2br"></span></a></p>
				</div>
				<div class="divider"></div>
			</div>

		</div>

	</div>

	<div class="divider dots spacer-one-two" ng-if="order.id"></div>

	<div class="content-padding" ng-if="order.id">
		<? /*
		<div class="credit" ng-if="!order.reward_delivery_free && (order.credit && order.credit > 0)">( ${{order._final_price}} - ${{order._credit}} credit )</div>
*/ ?>
		<a href="<?=$this->export ? '{{server}}' : ''?>printorder/{{ order.uuid }}" target="_system" class="print-icon"><button class="button lightorange"><i class="fa fa-print"></i>&nbsp;&nbsp;&nbsp;Print Receipt</button></a>
	</div>


</div>