<div class="restaurant-pic-wrapper">

	<div class="restaurant-pic hide-mobile"></div>
	<div class="restaurant-pic hide-desktop"><div class="restaurant-pic-overlay"></div></div>

	<div class="restaurant-content-padding">

		<div class="restaurant-name">
			<h1 ng-resize-text>One Button Wenzel</h1>
		</div>

		<div class="giftcard-badge" ng-if="credit.hasValue">
			<i class="fa fa-certificate"></i>
			<div class="giftcard-badge-value"><sup>$</sup>{{Math.round(credit.value)}}</div>
			<div class="giftcard-badge-text">gift card</div>
		</div>
	</div>

	<div class="divider"></div>
</div>